apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
#  minReadySeconds: 30
  replicas: 2
  selector:
    matchLabels:
      app: fe-deployment
      release: "v0"
  template:
    metadata:
      labels:
        app: fe-deployment
        release: "v0"
    spec:
      containers:
        - name: fe-deployment
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: fe-deployment
    release: "v0"
  type: NodePort
