apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-deployment
  template:
    metadata:
      labels:
        app: queue-deployment
    spec:
      containers:
        - name: queue-deployment
          image: richardchesterwood/k8s-fleetman-queue:release1

---
apiVersion: v1
kind: Service
metadata:
  name: queue-service
spec:
  ports:
    - name: http
      port: 8161
      targetPort: 8161
      nodePort: 30002
  selector:
    app: queue-deployment
  type: NodePort